import { cloneDeep, random } from 'lodash'

const defaultProfil = {
  id: null,
  title: null,
  surname: null,
  description: null,
  email: null,
  password: null,
  sexe: 'M',
  sexeSearch: 'F',
  age: null,
  localisation: '',
  publishDate: null,
  rangeAge: {
    min: 18,
    max: 99
  }
}

const tabSexe = ['M', 'F']
const labelSexe = {
  M: 'Homme',
  F: 'Femme'
}
const tabPrenom = {
  M: [
    'Gabriel',
    'Louis',
    'Raphaël',
    'Jules',
    'Adam',
    'Lucas',
    'Léo',
    'Hugo',
    'Arthur',
    'Nathan',
    'Liam',
    'Éthan',
    'Maël',
    'Paul',
    'Tom',
    'Sacha',
    'Noah',
    'Gabin',
    'Nolan',
    'Enzo',
    'Mohamed',
    'Aaron',
    'Timéo',
    'Théo',
    'Mathis',
    'Axel',
    'Victor',
    'Antoine',
    'Valentin',
    'Martin',
    'Noé',
    'Éden',
    'Robin',
    'Marius',
    'Rayan',
    'Clément',
    'Baptiste',
    'Maxime',
    'Samuel',
    'Léon',
    'Yanis',
    'Augustin',
    'Eliott',
    'Maxence',
    'Évan',
    'Mathéo',
    'Alexandre',
    'Thomas',
    'Simon',
    'Gaspard',
    'Naël',
    'Tiago',
    'Amir',
    'Isaac',
    'Nino',
    'Ibrahim',
    'Lyam',
    'Lenny',
    'Malo',
    'Imran',
    'Marceau',
    'Alexis',
    'Kaïs',
    'Camille',
    'Noa',
    'Oscar',
    'Noam',
    'Mathys',
    'Esteban',
    'Ayden',
    'Ilyes',
    'Lorenzo',
    'Kylian',
    'Adrien',
    'Côme',
    'Wassim',
    'Ismaël',
    'Soan',
    'Amine',
    'Youssef',
    'Naïm',
    'Milo',
    'Benjamin',
    'Ayoub',
    'Joseph',
    'Owen',
    'Ali',
    'William',
    'Jean',
    'Louka',
    'Adem',
    'Bastien',
    'Léandre',
    'Antonin',
    'Noham',
    'Logan',
    'Kenzo',
    'Younes',
    'Sandro',
    'David'
  ],
  F: [
    'Emma',
    'Louise',
    'Jade',
    'Alice',
    'Chloé',
    'Lina',
    'Mila',
    'Léa',
    'Manon',
    'Rose',
    'Anna',
    'Inès',
    'Camille',
    'Lola',
    'Ambre',
    'Léna',
    'Zoé',
    'Juliette',
    'Julia',
    'Lou',
    'Sarah',
    'Lucie',
    'Mia',
    'Jeanne',
    'Romane',
    'Agathe',
    'Éva',
    'Nina',
    'Charlotte',
    'Inaya',
    'Léonie',
    'Sofia',
    'Margaux',
    'Louna',
    'Clara',
    'Luna',
    'Maëlys',
    'Olivia',
    'Adèle',
    'Lilou',
    'Clémence',
    'Léana',
    'Lana',
    'Capucine',
    'Éléna',
    'Victoria',
    'Aya',
    'Mathilde',
    'Margot',
    'Iris',
    'Anaïs',
    'Giulia',
    'Alicia',
    'Romy',
    'Nour',
    'Élise',
    'Théa',
    'Yasmine',
    'Victoire',
    'Lya',
    'Mya',
    'Elsa',
    'Charlie',
    'Assia',
    'Lise',
    'Lily',
    'Noémie',
    'Emy',
    'Lisa',
    'Lyna',
    'Marie',
    'Soline',
    'Apolline',
    'Alix',
    'Gabrielle',
    'Valentine',
    'Louane',
    'Candice',
    'Pauline',
    'Faustine',
    'Héloïse',
    'Océane',
    'Inès',
    'Mélina',
    'Maya',
    'Thaïs',
    'Roxane',
    'Salomé',
    'Lila',
    'Maria',
    'Constance',
    'Célia',
    'Sara',
    'Livia',
    'Zélie',
    'Lyana',
    'Emmy',
    'Alya',
    'Élisa',
    'Maryam'
  ]
}
const tabHobbies = [
  'Aller en campagne',
  'Aller à la plage',
  'Aller à la pêche',
  'Se promener en montagnes',
  'Faire du camping',
  'Marcher en ville, faire du lèche-vitrine',
  'Visiter une autre ville',
  "Aller à un zoo, un carnaval, un cirque ou un parc d'amusement",
  'Aller au parc, à un piquenique ou un barbecue',
  'Aller à un ciné-parc, chez Dairy Queen, McDonald, etc.',
  'Visiter des endroits particuliers: aéroports, écluses,  endroits avec une vue particulière',
  'Sorties',
  'Aller à des rencontres de clubs sociaux ou civiques',
  'Aller à une soirée (party)',
  'Aller à un concert',
  'Aller aux courses (chevaux, auto, bateau, etc.)',
  'Aller à un bar, une taverne, un club, etc.',
  'Aller à une conférence',
  'Manger avec des amis',
  'Aller à un mariage, un baptême, une confirmation, etc.',
  'Chanter en groupe',
  "Aller à une organisation mise sur pied par l'église (cours, rencontres sociales, ventes, bingo)",
  'Aller à une réunion publique (souvenirs, bonne cause, etc.)',
  'Aller à un club de santé, un sauna, etc.',
  'Flirter, donner des rendez-vous, faire la cour, etc.',
  'Aller à la chasse ou au champ de tir',
  "Aller à un musée ou à une galerie d'art",
  'Aller visiter ses enfants, sa famille, sa parenté',
  'Aller à une pièce de théâtre',
  'Aller au cinéma',
  'Aller à la librairie ou à la bibliothèque',
  'Aller au magasin de disque',
  'Magasiner',
  'Assister à un concert, un opéra, ou un ballet',
  'Aller au restaurant',
  'Aller à un banquet, un brunch, etc.',
  'Aller à un encan, des ventes de garage, etc.',
  'Danser',
  "Aller chez le coiffeur ou l'esthéticienne",
  "Dormir à l'hôtel pour une nuit",
  'Sports',
  'Aller à des événements sportifs',
  'Prendre une marche',
  'Jouer au baseball ou à la balle molle-Jouer au golf',
  'Jouer au tennis',
  'Jouer au basketball',
  'Jouer au football',
  'Jouer au handball, au squash, etc.',
  'Escalader une montagne',
  'Naviguer (canot, cayak, bateau à moteur, à voile, etc.)',
  'Conduire une auto ou un bateau',
  'Aller faire du ski alpin ou du ski de fond',
  "Faire de l'équitation",
  'Jouer à des sports sur pelouse (badminton, croquet, fer à cheval, etc.)',
  'Regarder un combat',
  'Jouer au ping-pong',
  'Nager',
  'Courir, faire de la gymnastique, des exercices physiques, etc.',
  'Arts ou artisanat',
  "Faire une œuvre d'art (peinture, aquarelle, sculpture, dessin, film, etc.)",
  'Créer ou arranger des chansons ou de la musique',
  'Restaurer des antiquités, refaire les meubles',
  'Travailler le bois, la menuiserie',
  "Jouer d'un instrument de musique",
  'Jouer (acteur)',
  "Faire de l'artisanat (poterie, bijoux, cuir, tissage, etc.)",
  'La photographie',
  'Dessiner un vêtement',
  'Jouer dans un groupe musical',
  'Écouter de la musique',
  'Coudre',
  'Travail, réparation, rénovation',
  'Poser sa candidature à des emplois à temps partiel ou à temps plein, temporaires ou permanents',
  'Donner un discours ou une conférence',
  'Faire des petites réparations à la maison',
  "Jardiner, faire de l'aménagement paysagé ou travailler dans la cour extérieure",
  "Amasser des objets naturels (fruits ou nourritures sauvages, roches, bois sur le bord de l'eau, etc.)",
  'Travailler en politique',
  'Faire des travaux ménagers ou le lavage, laver des choses',
  'Réparer des choses',
  'Vendre des produits (Avon, Tupperware, etc.)',
  "Garder des enfants, gratuitement ou contre rémunération, régulièrement où à l'occasion",
  'Jeux',
  'Jouer aux cartes',
  'Résoudre un problème, un casse-tête, des mots croisés, mots cachés, etc.',
  'Jouer au billard',
  'Jouer aux quilles',
  'Jouer aux échecs ou aux dames',
  'Gager (gambling)',
  'Jouer à des jeux de société (Monopoly, Scrabble, backgammon, etc.)',
  'À la maison',
  'Aménager ou décorer sa chambre ou la maison',
  'Regarder la télévision',
  'Se parler',
  'Se raser',
  'Prendre une douche',
  'Prendre un bain seul ou avec votre partenaire',
  'Se maquiller, placer ses cheveux, etc.',
  'Se peigner ou se brosser les cheveux',
  'Laver ses cheveux',
  "Utiliser un parfum, de l'eau de toilette, une lotion après rasage",
  'Faire une sieste',
  'Chanter seul',
  'Écouter la radio',
  'Parler au téléphone',
  'Organiser une soirée (party)',
  'Relaxer',
  'Prendre soin des plantes de la maison',
  "Laver l'automobile",
  'Collectionner des choses',
  'Marcher autour de chez soi.',
  "Massages, caresses, contacts intimes et sensuels, faire l'amour.",
  'Lire et écrire',
  'Lire la bible ou un autre livre saint',
  'Lire un livre ou un article indiquant comment faire certaines choses',
  'Lire des nouvelles, des poèmes, des romans, ou des pièces de théâtre',
  'Écrire des romans, des nouvelles, pièces de théâtre ou de la poésie',
  'Lire des essais ou de la littérature professionnelle, technique ou académique',
  'Recevoir des lettres, des cartes postales, des cartes de vœux, ou des notes',
  'Écrire une conférence, un essai, un article, un rapport, un memo, etc.',
  'Écrire un journal',
  'Écrire des lettres, des cartes postales, des cartes de vœux,  ou des notes',
  'Lire des bandes dessinées',
  'Lire le journal',
  'Écrire des lettres aux journaux ou à mon député pour protester contre les conditions sociales, politiques ou environnementales',
  'Lire des magazines',
  "Lire des histoires à quelqu'un",
  'Vêtements',
  "Porter des vêtements dispendieux ou d'apparat",
  'Porter des vêtements de  sport',
  'Porter des vêtements propres',
  'Porter de nouveaux vêtements',
  'Finance et Achats',
  "S'acheter des choses",
  'Faire de la nourriture ou des objets pour vendre',
  'Acheter quelque chose pour sa famille',
  'Faire un budget, planifier mes finances',
  'Faire un achat',
  'Améliorer sa santé (faire réparer ses dents, nouvelles lunettes, changement de régime alimentaire, etc.)',
  'Emprunter quelque chose',
  'Vendre ou échanger quelque chose',
  'Rendre service, dons et charité',
  'Faire des dons à des institutions religieuses ou charitables',
  'Visiter les gens qui sont malades, inhibés ou en difficultés',
  'Faire plaisir à des gens de mon entourage',
  'Faire de la nourriture ou des objets pour donner',
  'Donner des cadeaux',
  "Aider quelqu'un",
  "Conseiller quelqu'un",
  "Présenter des gens que je crois potentiellement intéressés l'un à l'autre",
  "Enseigner à quelqu'un",
  'Rendre des services aux gens',
  "Faire du bénévolat auprès d'enfants, de personnes âgées, à l'hôpital ou ailleurs",
  'Voyages et déplacements',
  'Planifier des voyages ou des vacances',
  'Conduire sur une longue distance',
  "Prendre l'avion",
  'Regarder des cartes (routières, géographiques, etc.)',
  'Se promener dans une auto sportive ou dispendieuse',
  'Voyager en groupe',
  'Se promener en motoneige ou en quatre roues',
  'Alimentation',
  'Faire des collations',
  'Faire des conserves, congeler des produits, faire des réserves de nourritures, etc.',
  'Manger un bon repas',
  'Manger une collation',
  'Prendre du café, du thé, un cola, etc. avec des amis',
  'Préparer un met nouveau ou spécial',
  'Sujets de conversations',
  'Parler de mes loisirs ou de mes intérêts spéciaux (sports, voyages, automobile, émission de télévision ou de radio, musique, disques, spectacles, lectures, sorties, mode, achats, nourriture, nouvelles, santé)',
  'Parler de son enfance ou de souvenirs',
  'Parler de philosophie ou de religion',
  'Parler de ses enfants ou petits-enfants',
  "Critiquer quelqu'un",
  'Parler des autres',
  'Parler de mon travail',
  'Parler de politique ou d’affaires publiques',
  'Faire des farces',
  'Parler de sexualité',
  "Exprimer mon amour ou mon amitié à quelqu'un",
  'Activités mentales',
  'Penser à quelque chose de bon à venir',
  'Penser à soi-même et à ses problèmes',
  "Penser à des gens que j'aime bien",
  'Avoir un rêve éveillé',
  'Planifier ou organiser quelque chose',
  'Se souvenir du passé',
  'Planifier son horaire, gérer son temps',
  "Se souvenir d'un ami ou d'un proche décédé,",
  'Observer, admirer, contempler, gouter à un plaisir simple',
  "S'asseoir au soleil",
  'Marcher pieds nu',
  "Respirer de l'air propre",
  'Regarder le lever ou le coucher du soleil',
  'Faire voler un cerf-volant',
  'Jouer dans la neige',
  'Être avec des animaux',
  "S'occuper d'un animal (oiseau, chien, chat, poisson rouge, etc.)",
  'Écouter aux bruits de la nature',
  'Regarder un beau paysage',
  'Donner des coups de pieds dans des feuilles mortes, du sable, de la gravelle, etc.',
  'Jouer avec des animaux',
  'Observer les animaux sauvages',
  'Observer le ciel, les nuages ou une tempête',
  'Regarder les étoiles ou la lune',
  'Regarder ou sentir une fleur ou une plante',
  'Goûter à la paix et la tranquillité',
  "Être avec quelqu'un que l'on aime",
  'Observer les oiseaux',
  'Observer les gens',
  'Faire ou observer un feu',
  'Observer les beaux hommes ou les belles femmes',
  'Faire des choses avec les enfants',
  'Marcher sur la plage',
  'Spiritualité',
  'Dire une prière',
  'Ressentir la présence de Dieu dans ma vie',
  'Méditer ou faire du yoga.',
  'Se confesser',
  'Écouter un bon sermon',
  "Être avec d'autres",
  'Rencontrer des amis',
  'Inviter des amis à vous visiter',
  "Faire des compliments à quelqu'un",
  'Se faire masser ou frotter le dos',
  "Donner des massages ou frotter le dos de quelqu'un",
  'Écouter des farces',
  "S'embrasser",
  'Sourire aux gens',
  'Visiter des amis',
  'Demander un conseil',
  "Convaincre quelqu'un de votre point de vue",
  "Argumenter avec quelqu'un",
  "Demander de l'aide ou un conseil",
  "Observer des membres de ma famille ou des amis faire des choses qui me rendent fier d'eux",
  'Être avec ses petits-enfants',
  'Développer de nouvelles habiletés',
  'Parler une langue étrangère',
  "Suivre des cours de yoga, de relaxation, de relations humaines, de danse, de langue, de poterie, de dessin, de décoration, d’arrangements floraux, d'entretien des plantes, d'aménagement paysagé, etc.",
  'Faire des expériences scientifiques',
  "Retourner à l'école pour poursuivre ses études primaires, secondaires, collégiales ou universitaires."
]

const PopulateResult = {
  randomTab: tab => {
    return tab[random(0, tab.length - 1, false)]
  },

  randomTabN: (tab, max) => {
    const n = random(0, max, false)
    const result = []
    for (let i = 0; i <= n; i++) {
      result.push(PopulateResult.randomTab(tab))
    }
    return result.join(' ')
  },

  randomDate: (start, end) => {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
  },

  generateTitle: profil => {
    return `${labelSexe[profil.sexe]} recherche ${labelSexe[profil.sexeSearch]} pour ${PopulateResult.randomTab(tabHobbies)}`
  },

  generateProfil: () => {
    const profil = cloneDeep(defaultProfil)
    profil.id = Math.random()
      .toString(36)
      .replace(/[^a-zA-Z0-9]+/g, '')
      .substr(0, 15)
    profil.sexe = PopulateResult.randomTab(tabSexe)
    profil.surname = PopulateResult.randomTab(tabPrenom[profil.sexe])
    profil.sexeSearch = PopulateResult.randomTab(tabSexe)
    profil.age = random(18, 80, false)
    profil.localisation = 'Ligné'
    profil.description = PopulateResult.randomTabN(tabHobbies, 15)
    profil.rangeAge.min = random(18, 40, false)
    profil.rangeAge.max = random(40, 80, false)
    profil.title = PopulateResult.generateTitle(profil)
    profil.publishDate = PopulateResult.randomDate(new Date(2019, 6, 1), new Date())
    return profil
  },

  generateProfils: n => {
    const profils = []
    for (let i = 0; i <= n; i++) {
      profils.push(PopulateResult.generateProfil())
    }
    return profils
  }
}

export default PopulateResult
